DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS like;
DROP TABLE IF EXISTS tag;

CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL
);

CREATE TABLE post (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	author_id INTEGER NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	title TEXT NOT NULL,
	body TEXT NOT NULL,
	FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE comment (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	author_id INTEGER NOT NULL,
	post_id INTEGER NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	body TEXT NOT NULL,
	FOREIGN KEY (author_id) REFERENCES user (id),
	FOREIGN KEY (post_id) REFERENCES post (id)
);

CREATE TABLE like (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL,
	post_id INTEGER NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES user (id),
	FOREIGN KEY (post_id) REFERENCES post (id),
	CONSTRAINT user_post_like UNIQUE (user_id, post_id)
);

-- CREATE TABLE tag (
-- 	id INTEGER PRIMARY KEY AUTOINCREMENT,
-- 	name TEXT NOT NULL,
-- 	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
-- );

-- CREATE TABLE post_tag (
-- 	id INTEGER PRIMARY KEY AUTOINCREMENT,
-- 	post_id INTEGER NOT NULL,
-- 	tag_id INTEGER NOT NULL, 
-- 	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
-- 	FOREIGN KEY (post_id) REFERENCES post (id),
-- 	FOREIGN KEY (tag_id) REFERENCES tag (id),
-- 	CONSTRAINT post_tag_relation UNIQUE (post_id, tag_id)
-- );